{% set name = "tldr" %}
{% set version = "3.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 34f573fa8f65d6b484dab5c2d93392c11141fb44161d4651e21b925820c1303f

build:
  number: 0
  noarch: python
  entry_points:
    - tldr = tldr:cli
  script: curl https://raw.githubusercontent.com/tldr-pages/tldr-python-client/{{ version }}/requirements.txt > requirements.txt; {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - curl
  host:
    - pip
    - python {{ python_min }}
    - hatchling
  run:
    - shtab >=1.3.10
    - colorama
    - python >={{ python_min }}
    - termcolor

test:
  requires:
    - python {{ python_min }}
  commands:
    - tldr --help

about:
  home: https://github.com/tldr-pages/tldr-python-client
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: command line client for tldr

extra:
  recipe-maintainers:
    - ngam
    - izahn
