{% set name = "tldr" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8e243c20add63e8923d7b968b6854d8d41d443af5e8622880192d64e30208ba7

build:
  number: 1
  noarch: python
  entry_points:
    - tldr = tldr:cli
  script: curl https://raw.githubusercontent.com/tldr-pages/tldr-python-client/{{ version }}/requirements.txt > requirements.txt; {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - curl
  host:
    - pip
    - python {{ python_min }}
  run:
    - shtab
    - colorama
    - python >={{ python_min }}
    - termcolor

test:
  requires:
    - python {{ python_min }}
  commands:
    - tldr --help

about:
  home: https://github.com/tldr-pages/tldr-python-client
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: command line client for tldr

extra:
  recipe-maintainers:
    - ngam
    - izahn
